START_EPOCH: 0
WARMUP_EPOCHS: 3
WARMUP_LR: 2.0e-07
WEIGHT_DECAY: 0.9
BASE_LR: 2.0e-05
CLIP_GRAD: 5.0
EPOCHS: 20
LR_SCHEDULER:
  WARMUP_PREFIX: true
  NAME: cosine
MIN_LR: 2.0e-06
OPTIMIZER:
  BETAS:
  - 0.9
  - 0.999
  EPS: 1.0e-08
  NAME: adamw

