BASE_LR: 2.0e-05
CLIP_GRAD: 5.0
EPOCHS: 300
LR_SCHEDULER:
  DECAY_EPOCHS: 30
  DECAY_RATE: 0.1
  NAME: cosine
MIN_LR: 2.0e-06
OPTIMIZER:
  BETAS:
  - 0.9
  - 0.999
  EPS: 1.0e-08
  MOMENTUM: 0.9
  NAME: adamw
START_EPOCH: 0
WARMUP_EPOCHS: 20
WARMUP_LR: 2.0e-07
WEIGHT_DECAY: 0.05
